# docker-compose.ymlフォーマットのバージョン指定
version: '3'
services:
  # Railsコンテナ定義
  web:
    # Dockerfileを使用してイメージをビルド
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp:cached
      # cachedは、コンテナからホストへの書き込みはすぐだが、ホストからコンテナへの書き込みは遅延が許可される
      - public-data:/myapp/public
      - sockets:/myapp/tmp/sockets
      # - log-data:/myapp/log
    ports:
      - "3000:3000"
    # dbコンテナが先に起動するよう設定
    depends_on:
      - db
    # コンテナを起動しっぱなしにできる
    tty: true
    # pryを使用してデバッグができるよう設定
    stdin_open: true
  # MySQLコンテナ定義
  db:
    # mysqlを使用してコンテナ作成
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    # ローカル環境とDocker環境のポートフォワーディングを設定
    ports:
      - "3306:3306"
    # コンテナ内の環境変数を定義
    environment:
      # オプション。データベースの名前を指定
      MYSQL_DATABASE: app_development
      # MySQLにおけるスーパユーザのrootアカウントに設定するパスワードを指定
      MYSQL_ROOT_PASSWORD: password
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - sockets:/myapp/tmp/sockets
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  sockets:
  public-data:
  # tmp-data:
  # log-data:
  # db-data: